Drop down menu
LowriKate/Scoop pull request #61
Opened 2022-11-13 14:28 UTC by LowriKate

2022-11-14 09:32 UTC, silverlight513 requested changes

2022-11-14 09:32 UTC, silverlight513 commented on components/ToggleSwitch.tsx
> +    border-radius: 90px;
If you're looking to make a cricle or something, then you can use 50% as the value

2022-11-14 09:32 UTC, silverlight513 commented on .env
> +DB_URL=mongodb+srv://Scoop:Moronorenacoch@clustersofscoop.0olrge8.mongodb.net/?retryWrites=true&w=majority
.env files should not be committed. Can you add this file to the `.gitignore` file please (it's just a list of file and folder paths relative to its location

2022-11-26 18:39 UTC, LowriKate commented on components/Input.tsx
> +  font-size: 1rem;
The font becomes much smaller when I remove this.

2022-11-26 18:42 UTC, LowriKate commented on components/PageHeader/DropDownContainer.tsx
> +const DropDownContainer = styled("div")``;
Deleted, don't think I was using this anyway.

2022-11-26 19:25 UTC, silverlight513 approved these changes

2022-11-26 19:30 UTC, merged